version: '3.8'

services:
  app:
    image: acurast-processor-management-backend:latest
    ports:
      - 8002:9001
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    image: acurast-processor-management-backend:latest
    command: npm run typeorm:run-migrations
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    shm_size: '4gb'
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c maintenance_work_mem=256MB
      -c max_worker_processes=8
      -c max_parallel_workers=8
      -c max_parallel_workers_per_gather=4
      -c max_connections=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=52428kB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
